export const itemsList = [
    {
        id: 1,
        name: "iPhone 9",
        description: "An apple mobile which is nothing like apple",
        price: 549,
        availableItems: 94,
        category: "smartphones",
        imageUrl: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
    },
    {
        id: 2,
        name: "iPhone X",
        description: "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
        price: 899,
        availableItems: 34,
        category: "smartphones",
        imageUrl: "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
    },
    {
        id: 3,
        name: "Samsung Universe 9",
        description: "Samsung's new variant which goes beyond Galaxy to the Universe",
        price: 1249,
        availableItems: 36,
        category: "smartphones",
        imageUrl: "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
    },
    {
        id: 4,
        name: "OPPOF19",
        description: "OPPO F19 is officially announced on April 2021.",
        price: 280,
        availableItems: 123,
        category: "smartphones",
        imageUrl: "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
    },
    {
        id: 5,
        name: "Huawei P30",
        description: "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
        price: 499,
        availableItems: 32,
        category: "smartphones",
        imageUrl: "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
    },
    {
        id: 6,
        name: "MacBook Pro",
        description: "MacBook Pro 2021 with mini-LED display may launch between September, November",
        price: 1749,
        availableItems: 83,
        category: "laptops",
        imageUrl: "https://i.dummyjson.com/data/products/6/thumbnail.png",
    },
    {
        id: 7,
        name: "Samsung Galaxy Book",
        description: "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
        price: 1499,
        availableItems: 50,
        category: "laptops",
        imageUrl: "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
    },
    {
        id: 8,
        name: "Microsoft Surface Laptop 4",
        description: "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
        price: 1499,
        availableItems: 68,
        category: "laptops",
        imageUrl: "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
    },
    {
        id: 9,
        name: "Infinix INBOOK",
        description: "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
        price: 1099,
        availableItems: 96,
        category: "laptops",
        imageUrl: "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
    },
    {
        id: 10,
        name: "HP Pavilion 15-DK1056WM",
        description: "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
        price: 1099,
        availableItems: 89,
        category: "laptops",
        imageUrl: "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
    },
    {
        id: 11,
        name: "perfume Oil",
        description: "Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil",
        price: 13,
        availableItems: 65,
        category: "fragrances",
        imageUrl: "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
    },
    {
        id: 12,
        name: "Brown Perfume",
        description: "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
        price: 40,
        availableItems: 52,
        category: "fragrances",
        imageUrl: "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
    },
    {
        id: 13,
        name: "Fog Scent Xpressio Perfume",
        description: "Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men",
        price: 13,
        availableItems: 61,
        category: "fragrances",
        imageUrl: "https://i.dummyjson.com/data/products/13/thumbnail.webp",
    },
    {
        id: 14,
        name: "Non-Alcoholic Concentrated Perfume Oil",
        description: "Original Al Munakh® by Mahal Al Musk | Our Impression of Climate | 6ml Non-Alcoholic Concentrated Perfume Oil",
        price: 120,
        availableItems: 114,
        category: "fragrances",
        imageUrl: "https://i.dummyjson.com/data/products/14/thumbnail.jpg",
    },
    {
        id: 15,
        name: "Eau De Perfume Spray",
        description: "Genuine  Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality",
        price: 30,
        availableItems: 105,
        category: "fragrances",
        imageUrl: "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
    },
    {
        id: 16,
        name: "Hyaluronic Acid Serum",
        description: "L'OrÃ©al Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid",
        price: 19,
        availableItems: 110,
        category: "skincare",
        imageUrl: "https://i.dummyjson.com/data/products/16/thumbnail.jpg",
    },
    {
        id: 17,
        name: "Tree Oil 30ml",
        description: "Tea tree oil contains a number of compounds, including terpinen-4-ol, that have been shown to kill certain bacteria,",
        price: 12,
        availableItems: 78,
        category: "skincare",
        imageUrl: "https://i.dummyjson.com/data/products/17/thumbnail.jpg",
    },
    {
        id: 18,
        name: "Oil Free Moisturizer 100ml",
        description: "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
        price: 40,
        availableItems: 88,
        category: "skincare",
        imageUrl: "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
    },
    {
        id: 19,
        name: "Skin Beauty Serum.",
        description: "Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m",
        price: 46,
        availableItems: 54,
        category: "skincare",
        imageUrl: "https://i.dummyjson.com/data/products/19/thumbnail.jpg",
    },
    {
        id: 20,
        name: "Freckle Treatment Cream- 15gm",
        description: "Fair & Clear is Pakistan's only pure Freckle cream which helpsfade Freckles, Darkspots and pigments. Mercury level is 0%, so there are no side effects.",
        price: 70,
        availableItems: 140,
        category: "skincare",
        imageUrl: "https://i.dummyjson.com/data/products/20/thumbnail.jpg",
    },
    {
        id: 21,
        name: "- Daal Masoor 500 grams",
        description: "Fine quality Branded Product Keep in a cool and dry place",
        price: 20,
        availableItems: 133,
        category: "groceries",
        imageUrl: "https://i.dummyjson.com/data/products/21/thumbnail.png",
    },
    {
        id: 22,
        name: "Elbow Macaroni - 400 gm",
        description: "Product details of Bake Parlor Big Elbow Macaroni - 400 gm",
        price: 14,
        availableItems: 146,
        category: "groceries",
        imageUrl: "https://i.dummyjson.com/data/products/22/thumbnail.jpg",
    },
    {
        id: 23,
        name: "Orange Essence Food Flavou",
        description: "Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item",
        price: 14,
        availableItems: 26,
        category: "groceries",
        imageUrl: "https://i.dummyjson.com/data/products/23/thumbnail.jpg",
    },
    {
        id: 24,
        name: "cereals muesli fruit nuts",
        description: "original fauji cereal muesli 250gm box pack original fauji cereals muesli fruit nuts flakes breakfast cereal break fast faujicereals cerels cerel foji fouji",
        price: 46,
        availableItems: 113,
        category: "groceries",
        imageUrl: "https://i.dummyjson.com/data/products/24/thumbnail.jpg",
    },
    {
        id: 25,
        name: "Gulab Powder 50 Gram",
        description: "Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds",
        price: 70,
        availableItems: 47,
        category: "groceries",
        imageUrl: "https://i.dummyjson.com/data/products/25/thumbnail.jpg",
    },
    {
        id: 26,
        name: "Plant Hanger For Home",
        description: "Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf",
        price: 41,
        availableItems: 131,
        category: "home-decoration",
        imageUrl: "https://i.dummyjson.com/data/products/26/thumbnail.jpg",
    },
    {
        id: 27,
        name: "Flying Wooden Bird",
        description: "Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF, Laminated 3.5mm",
        price: 51,
        availableItems: 17,
        category: "home-decoration",
        imageUrl: "https://i.dummyjson.com/data/products/27/thumbnail.webp",
    },
    {
        id: 28,
        name: "3D Embellishment Art Lamp",
        description: "3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)",
        price: 20,
        availableItems: 54,
        category: "home-decoration",
        imageUrl: "https://i.dummyjson.com/data/products/28/thumbnail.jpg",
    },
    {
        id: 29,
        name: "Handcraft Chinese style",
        description: "Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate",
        price: 60,
        availableItems: 7,
        category: "home-decoration",
        imageUrl: "https://i.dummyjson.com/data/products/29/thumbnail.webp",
    },
    {
        id: 30,
        name: "Key Holder",
        description: "Attractive DesignMetallic materialFour key hooksReliable & DurablePremium Quality",
        price: 30,
        availableItems: 54,
        category: "home-decoration",
        imageUrl: "https://i.dummyjson.com/data/products/30/thumbnail.jpg",
    }
];